name: Weekly GSCI Update

on:
  schedule:
    - cron: '0 0 * * 1' # 每周一北京时间上午 8 点运行
  workflow_dispatch: # 允许你手动点击运行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libs
        run: pip install pandas google-cloud-bigquery db-dtypes

      - name: Run Script
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: python update_gsci.py

      - name: Auto Save to GitHub
        run: |
          git config --global user.name "GSCI-Bot"
          git config --global user.email "bot@gsci.com"
          git add gsci_data.csv
          git commit -m "Automated Data Update" || exit 0
          git push
